apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: iquantc/my-app:99766be499c1b78c719d1ace05020a6aeebbec60
        ports:
        - containerPort: 3000

