apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: iquantc/my-app:f1fe099d2713ceccc08679cb8716a15f6c3c4350
        ports:
        - containerPort: 3000

